<style>
table, th, td {
  border: 1px solid;
  padding: 8px;
}
table {
  border-collapse: collapse;
}
</style>

<h1>StockHive</h1>
<h2>Inventory Report</h2>
<h4>Date: {{ (new \DateTime())->format( 'd-m-Y' ); }}</h3>
<h4>Time: {{ (new \DateTime())->format( 'H:i:s' ); }}</h3>
<h4>Generated by: {{ $name }}</h3>
<table>
    <thead>
        <tr>
            <th>Product</th>
            @php $months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'] @endphp
            @foreach ($months as $month)
                <th>{{ $month }}</th>
            @endforeach
        </tr>
    </thead>
    <tbody>
        @foreach($allresults as $item)
            <tr>
                <td>{{ $item['item_name'] }}</td>
                @for ($month = 1; $month <= 12; $month++)
                    @php
                        // Check for the month in both numeric and string formats
                        $monthKey = array_key_exists($month, $item['data']) ? $month : sprintf('%02d', $month);
                    @endphp
                    @if (isset($item['data'][$monthKey]))
                        <td>£{{ $item['data'][$monthKey]['total'] }}</td>
                    @else
                        <td>£0</td>
                    @endif
                @endfor
            </tr>
        @endforeach
    </tbody>
</table>
